# Config PSF for CFHT observations

atmospheric:
  # Coefficient for the HV model at Mauna Kea
  # Cn2(h) = A1*exp(-h/H1) + A2*h**10*np.exp(-h/H2) + A3*np.exp(-(h-H3)**2./(2.*d**2))
  HV_coeff:
    # Needed to add a surface layer A0 to obtain results in agreement with 
    # measures done at the Mauna Kea. This can also be set to 0.
    A0: 1.e-15       # Surface turbulence (Cn^2(0))
    H0: 100.         # Limit for the surface turbulence
    A1: 1.0e-17      # Troposphere turbulence (up to 10km)
    H1: 3.0e+3       # (m)
    A2: 1.63e-53     # Turbulence peak at the tropopause
    H2: 1.0e+3       # (m)
    A3: 1.0e-16      # Isolated layer of turbulence
    H3: 6.5e+3       # (m)
    d: 300           # (m) Layer thickness

  # No models here
  # Provide "alts" and "L0" as lists under the corresponding keys
  # Values can be drawn from a Log-Normal distribution at each alts
  # using the provided sigma value (sigma is define on log(L0))
  L0_values:
    # in m
    alts:
      - 0.e+3
      - 2.e+3
      - 4.e+3
      - 8.e+3
      - 16.e+3
    # in m
    L0:
      - 17.4
      - 13.57
      - 15.19
      - 29.76
      - 33.54
    spread: True
    sig: 0.23

  wind:
    # Coefficient for the Greenwood model
    # W_speed = v_g + v_t * np.exp(-((h*np.cos(theta*np.pi/180.) - H)/T)**2.)
    GW_coeff:
      H: 12.0e+3    # (m) Height of tropopause
      T: 5.0e+3     # (m) Thickness of tropopause layer
    # Range of variation for the wind speed in the ground and 
    # troposphere layers
    # Provide as 2 sperate lists [min, max]
    # in m.s^-1
    wind_speed:
      ground:
        - 5.
        - 8.
      trop:
        - 15.
        - 30.
  seeing_distribution: "/Users/aguinot/Documents/pipeline/simu_MICE/test_new_LenSimu/all_star_fwhm.npy"
  simple_model:
    grid_size: 1024  # Grid size used to model the atmosphere over the FOV.

telescope:
  FOV: 1.2              # (deg) (1x1 deg2 is WITHOUT the ears!!)
  pixel_scale: 0.187    # arcsec/pixel
  aperture:
    # Needed to compute the size of the simulated screen
    diam: 3.58          # (m)
    obscuration: 0.38   # fraction of aperture
    nstruts: 4
    # strut_thick: 0.013   # fraction of aperture diameter
    strut_thick: 0.04   # fraction of aperture diameter
  pupil_plane_image: "/Users/aguinot/Documents/pipeline/simu_MICE/test_new_LenSimu/CFHT_pupil.fits.fz"
  lam: 640              # effective wavelenght in nm
  ccd_size: [2112, 4644]
  data_sec: [33, 2080, 1, 4612]
  saturate: 65535
  read_noise: 5
  focal_plane_file:
    e1: "/Users/aguinot/Documents/pipeline/simu_MICE/test_new_LenSimu/star_e1.npy"
    e2: "/Users/aguinot/Documents/pipeline/simu_MICE/test_new_LenSimu/star_e2.npy"
    size: "/Users/aguinot/Documents/pipeline/simu_MICE/test_new_LenSimu/star_size.npy"
    weights: "/Users/aguinot/Documents/pipeline/simu_MICE/test_new_LenSimu/ccd_weights.npy"
  header_info: "/Users/aguinot/Documents/pipeline/simu_MICE/test_new_LenSimu/P3_header_info.pkl"
  gain: "/Users/aguinot/Documents/pipeline/simu_MICE/test_new_LenSimu/ccd_gains.npy"

masking:
  weight_mask:
    make: True
    flag_value: 1
  border:  # For coadd, this will always be ignored
    make: True
    border_size: 50
    flag_value: 4
  halo_mask:
    make: True
    reg_path: "/Users/aguinot/Documents/pipeline/simu_MICE/test_new_LenSimu/halo_mask.reg"
    mag_limit: 13.
    scale_factor: 0.05
    mag_pivot: 13.8
    flag_value: 2
  spike_mask:
    make: True
    reg_path: "/Users/aguinot/Documents/pipeline/simu_MICE/test_new_LenSimu/MEGAPRIME_star_i_13.8.reg"
    mag_limit: 18.
    scale_factor: 0.3
    mag_pivot: 13.8
    flag_value: 128

simu:
  only_center: True  # If True, only simulate the central object (no stars, no neighbors)
  obj_stamp_size: 500  # galsim stamp size for all objects (in pixels)
  bright_obj_stamp_size: 1_000  # galsim stamp size for bright objects (in pixels)
  full_atm: False  # Wether to simulate the atmosphere with all complexity. Save compute time.
  varying_psf: False  # Wether to disable the PSF spatial variations.
                     # With the simple model it makes no difference Save compute time.
  save_psf: True   # Wether to save the PSFs. Save compute time.
  coadd_method: "swarp"  # Either "swarp" or "metacoadd"
  swarp_info:  # Only relevant if swarp is taken for coadding.
    run_dir: "/Users/aguinot/Documents/pipeline/simu_MICE/test_new_LenSimu/output_stamp/"  # Directory where to run SWARP (where the temporary file will be created).
    exec: "/Users/aguinot/Documents/library/swarp/src/swarp"  # Executable path of swarp
    config_path: "/Users/aguinot/Documents/pipeline/simu_MICE/test_new_LenSimu/config.swarp"  # Path to the swarp config file ".swarp"
  do_weight: True  # Wether to include weight (dead pixels/columns from real data)
  do_masking: True  # Wether to add mask
  noise_factor: 1.  # Multiplicative factor to artificial scale down/up the noise
  verbose: False

stamp:
  stamp_size: 151
  # stamp_size: 1000
  coadd_scale: 0.1857  # If using swarp for the coadd, depends on the config file of swarp
  coadd_info: "/Users/aguinot/Documents/pipeline/simu_MICE/test_new_LenSimu/coadd_info.pkl"

file:
  output_dir: "/Users/aguinot/Documents/pipeline/simu_MICE/test_new_LenSimu/output_single_obj/"
